### ISSUE TITLE
panic during normal execution

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/aysfs#20]
```
2016/02/22 11:51:03 rw I > Downloading file '/ays/backend/portal3-optvar/optvar/cfg/portals/example/base/home/.space/default.md' 
2016/02/22 11:51:03 rw I > Downloading: https://stor.jumpscale.org/storx/store/js8_optvar/bb2f3eac41f3c2478ca9c9660e414b00 
2016/02/22 11:52:06 rw I > Downloading file '/ays/backend/portal3-optvar/optvar/cfg/portals/portalbase/wiki/System/.files/css/flatTheme.css' 
2016/02/22 11:52:06 rw I > Downloading: https://stor.jumpscale.org/storx/store/js8_optvar/9ed53c3999490afce8844d35d8a6e845 
fatal error: concurrent map writes

goroutine 96703 [running]:
runtime.throw(0xa39220, 0x15)
        /usr/lib/go/src/runtime/panic.go:530 +0x90 fp=0xc829ca3008 sp=0xc829ca2ff0
runtime.mapassign1(0x853260, 0xc8200f7350, 0xc829ca30f8, 0xc829ca3118)
        /usr/lib/go/src/runtime/hashmap.go:445 +0xb1 fp=0xc829ca30b0 sp=0xc829ca3008
github.com/Jumpscale/aysfs/rw.(*factory).Get(0xc82018f8e0, 0xc829e68410, 0x4a, 0x0, 0x0, 0x1)
        /home/zaibon/dev/go/src/github.com/Jumpscale/aysfs/rw/factory.go:91 +0x108 fp=0xc829ca3138 sp=0xc829ca30b0
github.com/Jumpscale/aysfs/rw.(*factory).Dir(0xc82018f8e0, 0xc8203f2500, 0xc829e68410, 0x4a, 0xc829e74360, 0x0, 0x0)
        /home/zaibon/dev/go/src/github.com/Jumpscale/aysfs/rw/factory.go:78 +0x15d fp=0xc829ca31f0 sp=0xc829ca3138
github.com/Jumpscale/aysfs/rw.(*fsDir).Lookup(0xc829e74360, 0x7f3137f20358, 0xc82572e040, 0xc829dc2cc0, 0xb, 0x0, 0x0, 0x0, 0x0)
        /home/zaibon/dev/go/src/github.com/Jumpscale/aysfs/rw/dir.go:131 +0x79e fp=0xc829ca3340 sp=0xc829ca31f0
bazil.org/fuse/fs.(*Server).serve(0xc820232000, 0x7f3137e9c060, 0xc8269b02c0)
        /home/zaibon/dev/go/src/bazil.org/fuse/fs/serve.go:1014 +0x6809 fp=0xc829ca3f68 sp=0xc829ca3340
bazil.org/fuse/fs.(*Server).Serve.func1(0xc820232000, 0x7f3137e9c060, 0xc8269b02c0)
        /home/zaibon/dev/go/src/bazil.org/fuse/fs/serve.go:419 +0x6d fp=0xc829ca3f88 sp=0xc829ca3f68
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc829ca3f90 sp=0xc829ca3f88
created by bazil.org/fuse/fs.(*Server).Serve
        /home/zaibon/dev/go/src/bazil.org/fuse/fs/serve.go:420 +0x580

```

**Comment by zaibon** [comment]
I close for now, seems 344d3e42366808db6fc1114170261e3faca11718 fixed the issue
